    CREATE TABLE IF NOT EXISTS ratings
    (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        mpa_name VARCHAR(20) NOT NULL,
        UNIQUE(mpa_name)
    );

    CREATE TABLE IF NOT EXISTS genres
    (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR(25) NOT NULL,
        UNIQUE(name)
    );

    CREATE TABLE IF NOT EXISTS films
    (
        id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR(50) NOT NULL,
        description VARCHAR(250) NOT NULL DEFAULT '',
        release_date TIMESTAMP,
        duration INT NOT NULL,
        mpa_id INT
    );

    CREATE TABLE IF NOT EXISTS users
    (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        login VARCHAR(20),
        email VARCHAR(30),
        name VARCHAR(30),
        birthday TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS films_genre
    (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        film_id BIGINT NOT NULL REFERENCES films(id),
        genre_id INT NOT NULL REFERENCES genres(id),
        UNIQUE(film_id, genre_id)
    );

    CREATE TABLE IF NOT EXISTS film_likes
    (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        film_id BIGINT NOT NULL REFERENCES films(id),
        user_id BIGINT NOT NULL REFERENCES users(id)
    );

    CREATE TABLE IF NOT EXISTS user_friends
    (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT NOT NULL REFERENCES users(id),
        friend_id BIGINT NOT NULL REFERENCES users(id)
    );

CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,
    is_positive BOOLEAN NOT NULL,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    film_id BIGINT REFERENCES films(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS review_useful (
    review_id BIGINT REFERENCES reviews(id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    is_like BOOLEAN,
    PRIMARY KEY (review_id, user_id)
);

CREATE TABLE IF NOT EXISTS event_types (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_name VARCHAR(25) NOT NULL
);

CREATE TABLE IF NOT EXISTS event_operations (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_name VARCHAR(25) NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts TIMESTAMP BY DEFAULT AS CURRENT_TIMESTAMP NOT NULL,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    event_type_id INT REFERENCES event_types(id),
    operation_id INT REFERENCES event_operations(id),
    entity_id BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS directors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    director_name VARCHAR(75) NOT NULL
);

CREATE TABLE IF NOT EXISTS film_directors (
    director_id BIGINT REFERENCES directors(id) ON DELETE CASCADE,
    film_id BIGINT REFERENCES films(id) ON DELETE CASCADE,
    PRIMARY KEY (director_id, film_id)
);