CREATE TABLE IF NOT EXIST films
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(50) NOT NULL,
    description    VARCHAR(250) NOT NULL DEFAULT '',
    release_date   TIMESTAMP WITH TIMEZONE_,
    duration       int NOT NULL,
    rating_id      REFERENCES ratings(id)
);

CREATE TABLE IF NOT EXIST ratings
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mpa_name        VARCHAR(20) NOT NULL
);

CRETE TABLE IF NOT EXIST genre
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR (25) NOT NULL
);

CREATE TABLE IF NOT EXIST films_genre
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id     REFERENCES films(id) NOT NULL,
    genre_id    REFERENCES genres(id) NOT NULL
);

CREATE TABLE IF NOT EXIST users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login       VARCHAR(20) NOT NULL,
    email       VARCHAR(30) NOT NULL,
    name        VARCHAR(20),
    birthday    TIMESTAMP
);

CREATE TABLE IF NOT EXIST film_likes
(
    int BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id REFERENCES films(id) NOT NULL,
    user_id REFERENCES users(id) NOT NULL
);

CREATE TABLE IF NOT EXIST user_friends
(
    id BIGINT GENERATE BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id REFERENCES users(id) NOT NULL,
    friend_id REFERENCES users(id) NOT NULL,
    status VARCHAR(20) NOT NULL
);